workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
        pre-build:
          - yes | sdkmanager "platforms;android-35" "build-tools;35.0.0"
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
